# Generated by rspec-sinatra. (2016-11-28 14:07:34 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'lib/DbApp.rb')

require 'capybara'
require 'capybara/rspec'
require 'rspec'
require 'rack/test'
require 'Sinatra'


Capybara.app = DbApp

RSpec.configure do |config|
  config.include Capybara::DSL
  config.include Rack::Test::Methods


  config.expect_with :rspec do |expectations|

    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|

    mocks.verify_partial_doubles = true
  end
end
